# Generated by Django 5.2.10 on 2026-01-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='servers.server')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='environments.environmentmode')),
            ],
        ),
        migrations.CreateModel(
            name='OdooEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('is_enterprise', models.BooleanField(default=False)),
                ('python_version', models.CharField(max_length=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='environments.environment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OdooDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='environments.odooenvironment')),
            ],
        ),
        migrations.CreateModel(
            name='OdooConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='environments.odooenvironment')),
            ],
        ),
        migrations.CreateModel(
            name='OdooPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_type', models.CharField(choices=[('core', 'Core'), ('config', 'Config'), ('addons', 'Addons'), ('python', 'Python')], max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='environments.odooenvironment')),
                ('oca_addons', models.BooleanField(default=False)),
                ('other_addons', models.BooleanField(default=False)),
                ('own_addons', models.BooleanField(default=False)),
                ('store_addons', models.BooleanField(default=False)),
            ],
        ),
    ]
