# Generated by Django 5.2.10 on 2026-01-14 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='users.organization')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='ServerIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('is_public', models.BooleanField(default=False)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='servers.server')),
            ],
            options={
                'verbose_name': 'Server IP',
                'verbose_name_plural': 'Server IPs',
            },
        ),
        migrations.CreateModel(
            name='ServerProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='server_providers/logos/')),
            ],
            options={
                'verbose_name': 'Server Provider',
                'verbose_name_plural': 'Server Providers',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='servers.serverprovider'),
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('allow_ssh', models.BooleanField(default=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='servers.server')),
                ('public_keys', models.ManyToManyField(blank=True, related_name='server_users', to='users.sshpublickey')),
            ],
            options={
                'verbose_name': 'Server User',
                'verbose_name_plural': 'Server Users',
            },
        ),
    ]
